language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  provider: script
  script: "./travis.sh"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: Y5ImmVg6/6Aubw0WV64dTOw4c+lqX/r6fZ9ryfVsBfEN/T7OCovRztnkPWFgtsULyclgvJ/2hgHqAmxNppDbdSHR6COPLy95jUSeK9gQ1/AUrtvewl15EfssR4uKE8bPtQrmU2S6r1NrdmT/HOoeJ3b+Rk6H7ixRWGKIO85S9KKhTtLwgXkkuWa/HgXx1z6iALamri1TrU3YejCkaJbWFE3uJwndc+ehOATcUBERfePZXyb3qMPKd+ntcKGL/keuGIDRcwRBk0wlEph2nLJ2y7zLKQqkWPVlkdD4ZuUwa0fiwjyIes1nzRFDrxGX9GE13ejoh6UQJLnW38C0ofPSV3M6Ou8n6m/sUPgpZi2j7+BTaqsQnf8XwJrVsLrH9/ww997Dmt3BeoUNYVh87JWA1OqWxd33eRQcXno3yD37VP8JLnyxoNw8Y2b+WqCdFWmznfQw5R6QqvLcQZ+pTb1NC3FBxlfE9w8xmeWjy5PceWicIgE0aLG121iApQ9j135rUaOzMSKM9BQPEPXD/lxWPOrcgzlzvFP/8nL/hxoI0wa78dRrAGNfUK9Bja3SXLe9ht2nrNmCVlmD5je+z2EKJzd60GcSH0SVTEvqf6K/Wu5zKuzmSfyY1qKyCumGa3DYOwaVKlRWV1GWbAC9hAtUv6ZdD2LZvaNnxFvHFgtZkTI=
